// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNgTltB06CCjCyYX8L0r0Zt1Vhen7BJMk',
    appId: '1:798670958966:web:1209b78a02f0ec30470a57',
    messagingSenderId: '798670958966',
    projectId: 'oruemstamp',
    authDomain: 'oruemstamp.firebaseapp.com',
    storageBucket: 'oruemstamp.appspot.com',
    measurementId: 'G-N9RTKX177D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFJQIEwTXGqB4X1AO16gWi1nPFPdIt44A',
    appId: '1:798670958966:android:0148233ea3ac2fbc470a57',
    messagingSenderId: '798670958966',
    projectId: 'oruemstamp',
    storageBucket: 'oruemstamp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1fsoyXQDliW8G8YEL915kybjvqkdlNuY',
    appId: '1:798670958966:ios:7dbfb87adfe2b974470a57',
    messagingSenderId: '798670958966',
    projectId: 'oruemstamp',
    storageBucket: 'oruemstamp.appspot.com',
    iosClientId:
        '798670958966-0f7gpvfovg5jar1qpvq3cu5nrgaal262.apps.googleusercontent.com',
    iosBundleId: 'com.example.oruemDojang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1fsoyXQDliW8G8YEL915kybjvqkdlNuY',
    appId: '1:798670958966:ios:86c31c3518101d53470a57',
    messagingSenderId: '798670958966',
    projectId: 'oruemstamp',
    storageBucket: 'oruemstamp.appspot.com',
    iosClientId:
        '798670958966-jot96sutf5k3bnfc1rv0lb3tbk2shrqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.oruemDojang.RunnerTests',
  );
}
